name: CodSpeed

on:
  push:
    branches:
      - "main" # or "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.PAT }}

      - run: git config --global url."https://not-matthias:${{ secrets.PAT }}@github.com".insteadOf "https://github.com"

      - name: Build the benchmark target(s)
        run: |
          ls
          mkdir cmake-build-benchmarks
          cd cmake-build-benchmarks
          cmake ../tests/benchmarks -DCMAKE_BUILD_TYPE=Release -DCODSPEED_MODE=instrumentation
          make -j12


      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cmake-build-benchmarks/json_benchmarks
          token: ${{ secrets.CODSPEED_TOKEN }}
          upload-url: https://api.staging.preview.codspeed.io/upload

  benchmarks-walltime:
    name: Run walltime benchmarks
    runs-on: codspeed-macro
    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.PAT }}

      - run: git config --global url."https://not-matthias:${{ secrets.PAT }}@github.com".insteadOf "https://github.com"

      - name: Build the benchmark target(s)
        run: |
          ls
          mkdir cmake-build-benchmarks
          cd cmake-build-benchmarks
          cmake ../tests/benchmarks -DCMAKE_BUILD_TYPE=Release -DCODSPEED_MODE=instrumentation
          make -j12


      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cmake-build-benchmarks/json_benchmarks
          token: ${{ secrets.CODSPEED_TOKEN }}
          upload-url: https://api.staging.preview.codspeed.io/upload
